name: Deploy Spring Boot Lambda to AWS

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Choose your AWS region

    - name: Deploy to AWS Lambda
      run: |
        # Package the Spring Boot application for Lambda deployment
        mvn clean package -Paws-lambda
        # Deploy to AWS Lambda
        aws lambda update-function-code \
      --function-name lambdafilehandler \
      --zip-file fileb://target/lambdafilehandler-0.0.1.jar
